### ISSUE TITLE
diagram generate: Authorization required, but no authorization protocol specified

### ISSUE THREAD

**Issue by jayvdb** [tmorin/plantuml-generator#10]
I see this message, and the png is generated.  It looks like this error is coming from the jar, not the Rust code.
```
> plantuml-generator diagram generate -f
[INFO  plantuml_generator::cmd::diagram::generate] source_directory: .
[INFO  plantuml_generator::cmd::diagram::generate] cache_directory: .cache
[INFO  plantuml_generator::cmd::diagram::generate] plantuml_jar: .cache/plantuml-1.2022.4.jar
[INFO  plantuml_generator::cmd::diagram::generate] java_binary: java
[INFO  plantuml_generator::cmd::diagram::generate] force_generation: true
[INFO  plantuml_generator::plantuml] the PlantUML jar is already there
[INFO  plantuml_generator::cmd::diagram::generate] generate "path/to/diagram.puml"
Authorization required, but no authorization protocol specified
```

**Comment by tmorin** [comment]
Hi @jayvdb,
I guess the issue is not related to `plantuml-generator` too.
Can you share the PlantUML file?
Best regards

**Comment by jayvdb** [comment]
Strangely, I am not seeing this message any more.

Thank you for all the fixes you have done.
We are now able to switch our docs [cargo-make](https://github.com/sagiegurari/cargo-make) tasks to using 

```toml
[tasks.convert-plantumls-to-svg]
install_crate = { crate_name = "plantuml-generator", binary = "plantuml-generator", force = false, test_arg = "--help" }
install_crate_args = ["--git", "https://github.com/tmorin/plantuml-generator", "--rev", "v1.14.0"]
command = "plantuml-generator"
args = ["diagram", "generate", "--force", "--args=-svg"]
env = { "PLANTUML_GENERATOR_OUTPUT_CACHE" = "${HOME}/.cache/plantuml-generator" }
```

We use a cache directory override because we use this task in a few repos, and want the jar file to be downloaded once for all repos.

And `--force` is needed to be confident the files are always processed.

It would be great if this crate could be published to crates.io , so that our task doesnt need to fetch the repo and pin to a github tag.
